### ISSUE TITLE
error on deleting old snapshots

### ISSUE THREAD

**Issue by sabinlazar** [bdeitte/scheduled-snapshots#5]
Hello. The first time the script had to delete old snaphots I got the following errors. Can you please check why that happens? Thanks!

[root@ip-172-]# python3 /usr/local/bin/ssbackup.py --volume-ids=vol-xxxxx1,vol-xxxxxc,vol-1xxxxxa --expiry-days=3
Creating snapshots...
Deleting old snapshots...
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/json/decoder.py", line 368, in raw_decode
    obj, end = self.scan_once(s, idx)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/ssbackup.py", line 128, in <module>
    deleteOldSnapshots(getOurSnapshots(), args.expiry_days)
  File "/usr/local/bin/ssbackup.py", line 103, in deleteOldSnapshots
    "--profile", profile
  File "/usr/local/lib/python3.3/json/**init**.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.3/json/decoder.py", line 352, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.3/json/decoder.py", line 370, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[root@ip-172-]#

**Comment by bdeitte** [comment]
Ah, so this is the same kind of problem you were originally having- your version of the AWS CLI for some reason does not return any response on some successful calls.  There's a simple fix for this, will add that in shortly.

**Comment by sabinlazar** [comment]
Thanks for the fix!
